version: '3.8'

services:
  app:
    build:
      context: client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app

  server:
    build:
      context: server
    ports:
      - 4000:4000
    volumes:
      - ./server:/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: bharg
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    tty: true

  migration:
    build:
      context: server
    command: '/app/auto/migrate'
    links:
      - db
    depends_on:
      - db
    env_file: ./server/.env
    volumes:
      - ./auto:/app
    # environment:
    #   - DB_HOST=database_application

volumes:
  pg_data: null
