version: '3.8'

services:
  app:
    build:
      context: client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app

  server:
    build:
      context: server
    ports:
      - 4000:4000
    volumes:
      - ./server:/app

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: bharg
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./server/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
